== *Uygulama içerisinde kısaca yaptıklarım*

> splash screen den sonra ana ekranda görünecek olan layout yapısını oluşturmak

> oluşturulan butonların işlevselliğini sağlamak için gerekli bağlantıları yapıp kodlamalarının yapılması.

> google play servisini kullanarak uygulamaya geçiş reklamı ve banner reklamı yerleştirmek ve gerekli yayıncı idsini almak .

> firebase notificon özelliğini kullanarak bildiri göndermek için gerekli google işlemlerini yapıp java dosyalarının kodlamak. 



* musics.xml dosyası oluşturuldu
* prev-back-stop-play butonları oluşturuldu.

---

  <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textAppearance="?android:attr/textAppearanceMedium"
        android:text="NEY DİNLETİLERİ"
        android:gravity="center"
        android:id="@+id/textTitle"
        android:layout_gravity="center"
        android:layout_alignParentTop="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:textSize="28dp"
        android:textColor="#000">
    </TextView>


    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center_horizontal"
        android:orientation="horizontal"
        android:id="@+id/linearLayout"
        android:layout_alignParentBottom="true"
        android:layout_alignParentStart="true">


        <ImageButton
            android:id="@+id/media_rew"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="2dp"
            android:onClick="rewind"
            android:src="@android:drawable/ic_media_rew" />

        <ImageButton
            android:id="@+id/media_pause"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="14dp"
            android:onClick="pause"
            android:src="@android:drawable/ic_media_pause" />

        <ImageButton
            android:id="@+id/media_play"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="14dp"
            android:onClick="play"
            android:src="@android:drawable/ic_media_play" />

        <ImageButton
            android:id="@+id/media_ff"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="14dp"
            android:onClick="forward"
            android:src="@android:drawable/ic_media_ff"

            />
    </LinearLayout>
    <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textAppearance="?android:attr/textAppearanceSmall"
            android:id="@+id/gettext"
            android:textColor="#ff00ebdd"
            android:layout_above="@+id/seekBar"
            android:layout_centerHorizontal="true" />
            


---
    
    * Pesrevler.java dosyası oluşturuldu ve kodlama yapıldı 
    
    
---
    
    public class Pesrevler extends ActionBarActivity {
    private static final String[] items={"Ağıt",
            "Asude",
            "Bahar",
            "Beyhude",
            "Bir Eski İstanbul",
            "Çeçen Kızı",
            "Dostluk",
            "Gurbet",
            "Hasbihal",
            "Kar Çiçekleri",
            "Kervan",
            "Mektup",
            "Pervane",
            "Rüzgarda Başaklar",
            "Senden Kalan",
            "Sonbahar",
            "Son Kuşlar",
            "Uzakta",
            "Yaban Gülü",
            "Yakamoz",
    };
    private final int[] resID = { R.raw.agit,
            R.raw.asude,
            R.raw.bahar,
            R.raw.beyhude,
            R.raw.bireskiistanbul,
            R.raw.cecenkizi,
            R.raw.dostluk,
            R.raw.gurbet,
            R.raw.hasbihal,
            R.raw.karcicekleri,
            R.raw.kervan,
            R.raw.mektup,
            R.raw.pervane,
            R.raw.ruzgardabasaklar,
            R.raw.sendenkalan,
            R.raw.sonbahar,
            R.raw.sonkuslar,
            R.raw.uzakta,
            R.raw.yabangul,
            R.raw.yakamoz,
    };

    private MediaPlayer mediaPlayer;
    public TextView duration,title,tv;
    private int timeElapsed = 0, finalTime = 0;
    private Handler durationHandler = new Handler();
    private SeekBar seekbar;
    private ListView musics;
    private ImageButton btnnext,btnprev;
    private int currentSongIndex ;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.musics);
        title= (TextView) findViewById(R.id.textTitle);
        Typeface face= Typeface.createFromAsset(getAssets(), "fonts/com.ttf");
        title.setTypeface(face);


        mediaPlayer = new MediaPlayer();
        btnnext = (ImageButton) findViewById(R.id.media_ff);
        btnprev = (ImageButton) findViewById(R.id.media_rew);
        musics = (ListView) findViewById(R.id.song_list);
        tv= (TextView) findViewById(R.id.gettext);

        ArrayAdapter<String> veriAdaptoru = new ArrayAdapter<String>(this,
                R.layout.list_image, R.id.list_content, items);
        musics.setAdapter(veriAdaptoru);


        musics.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                currentSongIndex=position;
                playSong(position);
            }
        });


        btnnext.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                currentSongIndex = currentSongIndex + 1;
                if (currentSongIndex == 20) {
                    Toast.makeText(getApplicationContext(), "Son Şarkı.", Toast.LENGTH_SHORT).show();
                    currentSongIndex = -1;
                } else
                    playSong(currentSongIndex);
            }
        });

        btnprev.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                currentSongIndex--;
                if (currentSongIndex == -1) {
                    Toast.makeText(getApplicationContext(), "Daha Fazla Gidilemez.", Toast.LENGTH_SHORT).show();
                    currentSongIndex = 0;
                } else
                    playSong(currentSongIndex);
            }
        });


    }


    public void play(View view) {
        mediaPlayer.start();

    }

    public void pause(View view) {
        mediaPlayer.pause();
    }

    private Runnable updateSeekBarTime = new Runnable() {
        public void run() {
            //get current position
            timeElapsed = mediaPlayer.getCurrentPosition();
            //set seekbar progress
            seekbar.setProgress((int) timeElapsed);
            //set time remaing
            double timeRemaining = finalTime - timeElapsed;
            duration.setText(String.format("%d:%d", TimeUnit.MILLISECONDS.toMinutes((long) timeRemaining), TimeUnit.MILLISECONDS.toSeconds((long) timeRemaining) - TimeUnit.MINUTES.toSeconds(TimeUnit.MILLISECONDS.toMinutes((long) timeRemaining))));
            //repeat yourself that again in 100 miliseconds
            durationHandler.postDelayed(this, 100);
        }
    };

    private void playSong(final int position) {

        mediaPlayer.reset();
        mediaPlayer=MediaPlayer.create(getApplicationContext(), resID[position]);
        finalTime = mediaPlayer.getDuration();
        duration = (TextView) findViewById(R.id.songDuration);
        seekbar = (SeekBar) findViewById(R.id.seekBar);
        seekbar.setMax((int) finalTime);
        seekbar.setClickable(false);
        timeElapsed = mediaPlayer.getCurrentPosition();
        seekbar.setProgress((int) timeElapsed);
        durationHandler.postDelayed(updateSeekBarTime, 100);

        String text = (String) musics.getItemAtPosition(position);
        tv.setText("Çalan Eser : "+text);
        seekbar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
            @Override
            public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
                if (fromUser) {
                    mediaPlayer.seekTo(progress);
                }
            }
            @Override
            public void onStartTrackingTouch(SeekBar seekBar) {
            }
            @Override
            public void onStopTrackingTouch(SeekBar seekBar) {
            }
        });
        mediaPlayer.start();

        mediaPlayer.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
            @Override
            public void onCompletion(MediaPlayer mp) {
                nextSong();

            }
        });
    }

    private void nextSong() {
        currentSongIndex = currentSongIndex + 1;
        if (currentSongIndex == 20) {
            Toast.makeText(getApplicationContext(), "Son Şarkı.", Toast.LENGTH_SHORT).show();
            currentSongIndex = -1;
        } else
            playSong(currentSongIndex);
    }


    @Override
    protected void onDestroy() {
        super.onDestroy();
        if(mediaPlayer!=null)
            mediaPlayer.stop();
    }
    
    
    
---

* Firebase bağlantısını sağlamak için MyFirebaseInstanceIDService.java ve MyFirebaseMessagingService.java dosyaları oluşturuldu.

---

** MyFirebaseInstanceIDService.java

package com.example.eozanozturk.neydinletileri;

import android.util.Log;

import com.google.firebase.iid.FirebaseInstanceId;
import com.google.firebase.iid.FirebaseInstanceIdService;

/**
 * Created by ibokan on 28.12.2016.
 */

public class MyFirebaseInstanceIDService extends FirebaseInstanceIdService {
    private static final String TAG = "MyFirebaseIIDService";

    @Override
    public void onTokenRefresh() {
        String token = FirebaseInstanceId.getInstance().getToken();
        Log.d(TAG, "Token: " + token);
        sendRegistrationToServer(token);

    }
    private void sendRegistrationToServer(String token) {
        // token'ı servise gönderme işlemlerini bu methodda yapmalısınız
    }
}

---

** MyFirebaseMessagingService.java

---

package com.example.eozanozturk.neydinletileri;

import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.support.v7.app.NotificationCompat;
import android.util.Log;

import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;


public class MyFirebaseMessagingService extends FirebaseMessagingService {

    private static final String TAG = "MyFirebaseMsgService";

    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        if (remoteMessage.getData().size() > 0) {
            // Data mesajı içeriyor mu
            //Uygulama arkaplanda veya ön planda olması farketmez. Her zaman çağırılacaktır.
            //Gelen içerik json formatındadır.
            Log.d(TAG, "Mesaj data içeriği: " + remoteMessage.getData());

            //Json formatındaki datayı parse edip kullanabiliriz.
            // Biz direk datayı Push Notification olarak bastırıyoruz

            sendNotification("ibokngl",""+remoteMessage.getData());
    }
}

    private void sendNotification(String messageTitle,String messageBody) {
        Intent intent = new Intent(this, Pesrevler.class);
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);

        PendingIntent pendingIntent = PendingIntent.getActivity(this, 0 /* Request code */, intent,
                PendingIntent.FLAG_ONE_SHOT);

        long[] pattern = {500,500,500,500};//Titreşim ayarı

        android.support.v4.app.NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this)
                .setSmallIcon(R.drawable.common_google_signin_btn_icon_dark)
                .setContentTitle(messageTitle)
                .setContentText(messageBody)
                .setAutoCancel(true)
               // .setVibrate(pattern)
                .setContentIntent(pendingIntent);

        NotificationManager notificationManager =
                (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);

        try {
            //    Uri alarmSound = Uri.parse(ContentResolver.SCHEME_ANDROID_RESOURCE + "://" + this.getPackageName() + "/raw/notification");
            //    Ringtone r = RingtoneManager.getRingtone(this, alarmSound);
            //   r.play();
        } catch (Exception e) {
            e.printStackTrace();
        }

        notificationManager.notify(0 /* ID of notification */, notificationBuilder.build());
    }
    }


---
